name: Build ROM
on:
  workflow_dispatch:

env:
  RELEASE_GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}

jobs:
  build:
  environment: 
    name: Builder
    url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }
  runs-on: self-hosted
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Disable git
      run: rm -rf .git

    - name: Build
      run: bash build.sh