on:
  workflow_dispatch:
 
jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Upload modules to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./out/target/product/vince/*.zip
          overwrite: false
